FROM webhippie/alpine:latest-amd64@sha256:40a95499bbc8cdb829680e3f021952532df63a613810561f4e2c09e02ffd297c

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  yarn global add gulp grunt-cli bower && \
  rm -rf /var/cache/apk/*
