FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:f2a9d34a6b2c077d31fc74f1fbbe34481ae06cabd73564890c83df1b9f7edcbf

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  yarn global add gulp grunt-cli bower && \
  rm -rf /var/cache/apk/*
