FROM webhippie/alpine:latest-arm64@sha256:205b666aaace58bc17b78f20521d0b153f0fc912b013238f58e262cd766ac321

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  yarn global add gulp grunt-cli bower && \
  rm -rf /var/cache/apk/*
