FROM webhippie/alpine:latest-arm@sha256:9a3e8aa27c9424fb3653885206dd671901d933be8d9ed41474a632c1af05ae84

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  rm -rf /var/cache/apk/*

RUN yarn global add gulp grunt-cli bower
