FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:0dfcbf91ff95665b3b4fdc18b2f3bc1594a45f53d56f0475d0d13a39de6a1798

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  yarn global add gulp grunt-cli bower && \
  rm -rf /var/cache/apk/*
