FROM webhippie/alpine:latest-arm@sha256:e462dace6c7fc76c0d8b3e1eeaff1f8cfd7d1af73e85facefbfb37b85ea221bc

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  yarn global add gulp grunt-cli bower && \
  rm -rf /var/cache/apk/*
