FROM webhippie/alpine:latest-arm@sha256:a6795fce5bd6079752399f32e738aebe02b07b4fb6192e5c2813d243563cd2b2

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  rm -rf /var/cache/apk/*

RUN yarn global add gulp grunt-cli bower
