FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:186cfab6fe45db91ce80ce4a86729a9f47db6e08afeb3805c74e29c59ed62b81

WORKDIR /srv/app

COPY ./overlay /

RUN apk update && \
  apk upgrade && \
  apk add build-base git nodejs-dev nodejs npm yarn file autoconf automake && \
  yarn global add gulp grunt-cli bower && \
  rm -rf /var/cache/apk/*
