#!/usr/bin/env bash
# Usage: manage console
# Summary: Start an interactive console
# Help: This command is used to start an interactive console on the container.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

node $@
